# Relative to root directory
siteconfig:
  deployFolder: 'deploy'
  demosFolder: 'demos'
  sourceFolder: 'source'
  layoutsFolder: 'layouts'
  panelCSS: 'panel.css'
  panelJS: 'modernizr.js'
  panelClass: 'sd-panel'
  panelTag: 'div'

# Allowed tags: javascript, forms, canvas, content, parser, svg, css, audio, video, webgl
demos:
  - slug: inbox-attack
    title: "Inbox Attack"
    tags: [svg]
    support: [svg]

  - slug: slideshows 
    title: "Slides from Web Openers"
    tags: [css]
    support: [pagedcontent]

  - slug: border-salon
    title: "Border Radius Salon"
    tags: [css]
    support: [borderradius]

  - slug: photo-booth
    title: "Photobooth in Your browser"
    tags: [javascript, canvas]
    support: [getusermedia, video]

  - slug: planetarium
    title: "HTML5 Planetarium"
    tags: [css]
    support: [csstransforms, csstransitions]

  - slug: touch-tracker
    title: "Simple multitouch demonstration"
    tags: [canvas]
    support: [canvas, touch]

  - slug: hixie-keyboard
    title: "Hixie Keyboard"
    tags: [audio, video, css]
    support: [audio, video]

  - slug: fence
    title: "Fence"
    tags: [css, svg]
    support: [svg, inlinesvg, bgrepeatround]

  - slug: paranoid
    title: "Return of the Retro with a canvas game!"
    tags: [canvas]
    support: [canvas]

  - slug: object-fitness
    title: "Object Fit"
    tags: [css]
    support: [object-fit]

  - slug: rock-piano
    title: "Rock Piano"
    tags: [css, audio]
    support: [audio]

  - slug: tatami
    title: "Tatami"
    tags: [css]
    support: [csstransitions]

  - slug: isometric-city
    title: "An isometric world"
    tags: [css]
    support: [csstransitions]

  - slug: picture-organizer
    title: "Touch-enabled photo lightbox"
    tags: [css, touch]
    support: [touch]

  - slug: border-radius-fun
    title: "Tinkering with Border Radius"
    tags: [css]
    support: [borderradius]

  - slug: tweetmap
    title: "A map of tweets from the public timeline"
    tags: [svg]
    support: [svg]

  - slug: 3d-color-histogram
    title: "3D color histogram"
    tags: [webgl]
    support: [canvas, video, webgl, webworkers]

  - slug: qr-code
    title: "QRY {curie} QR code reader"
    tags: [getusermedia]
    support: [getusermedia, video]

  - slug: world-flights
    title: "World flights"
    tags: [webgl]
    support: [canvas, webgl, webworkers]

  - slug: cosmonaut
    title: "First space walk"
    tags: [webgl]
    support: [canvas, webgl]

# Supported features list. Based on custom Modernizr build
features:
  - slug: applicationcache
    title: "App Cache"
    link: "http://www.whatwg.org/specs/web-apps/current-work/multipage/offline.html"

  - slug: audio
    title: "HTML Audio"
    link: "http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#audio"

  - slug: backgroundsize
    title: "CSS background-size"
    link: "http://www.w3.org/TR/css3-background/#the-background-size"

  - slug: bgrepeatround
    title: "CSS background-repeat: round"
    link: "http://www.w3.org/TR/css3-background/#background-repeat"

  - slug: bgrepeatspace
    title: "CSS background-repeat: space"
    link: "http://www.w3.org/TR/css3-background/#background-repeat"

  - slug: bgrepeatspace
    title: "CSS background-repeat: space"
    link: "http://www.w3.org/TR/css3-background/#background-repeat"

  - slug: borderimage
    title: "CSS border-image"
    link: "http://www.w3.org/TR/css3-background/#the-border-image"

  - slug: borderradius
    title: "CSS border-radius"
    link: "http://www.w3.org/TR/css3-background/#the-border-radius"

  - slug: boxshadow
    title: "CSS box-shadow"
    link: "http://www.w3.org/TR/css3-background/#box-shadow"

  - slug: canvas
    title: "Canvas"
    link: "http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#the-canvas-element"

  - slug: canvastext
    title: "Canvas Text"
    link: "http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#drawing-text-to-the-canvas"

  - slug: cssanimations
    title: "CSS Animations"
    link: "http://www.w3.org/TR/css3-animations/"

  - slug: csscolumns
    title: "CSS Multi-column"
    link: "http://www.w3.org/TR/css3-multicol/"

  - slug: cssgradients
    title: "CSS Gradients"
    link: "http://www.w3.org/TR/css3-images/#gradients"

  - slug: csstransforms
    title: "CSS 2D Transforms"
    link: "http://www.w3.org/TR/css3-2d-transforms/"

  - slug: csstransforms3d
    title: "CSS 3D Trnasforms"
    link: "http://www.w3.org/TR/css3-3d-transforms/"

  - slug: csstransitions
    title: "CSS Transitions"
    link: "http://www.w3.org/TR/css3-transitions/"

  - slug: draganddrop
    title: "http://www.whatwg.org/specs/web-apps/current-work/multipage/dnd.html#dnd"
    link: "HTML Drag and Drop"

  - slug: flexbox
    title: "http://www.w3.org/TR/css3-flexbox/"
    link: "CSS Flexbox"

  - slug: fontface
    title: "CSS Web Fonts"
    link: "http://www.w3.org/TR/css3-webfonts/"

  - slug: generatedcontent
    title: "CSS Generated Content"
    link: "http://www.w3.org/TR/CSS21/generate.html"

  - slug: geolocation
    title: "Geolocation API"
    link: "http://www.w3.org/TR/geolocation-API/"

  - slug: getusermedia
    title: "WebRTC getUserMedia"
    link: "http://www.w3.org/TR/webrtc/"

  - slug: hashchange
    title: "HTML hashChange event"
    link: "http://www.w3.org/TR/html5/history.html#event-hashchange"

  - slug: history
    title: "HTML History and Location API"
    link: "http://www.w3.org/TR/html5/history.html"

  - slug: hsla
    title: "CSS HSLA colors"
    link: "http://www.w3.org/TR/css3-color/#hsla-color"

  - slug: indexeddb
    title: "Indexed Database API"
    link: "http://www.w3.org/TR/IndexedDB/"

  - slug: inlinesvg
    title: "Inline SVG"
    link: "http://dev.w3.org/html5/spec/svg-0.html"

  - slug: js
    title: "JavaScript"
    link: "TODO: find better link"

  - slug: localstorage
    title: "Web Storage localStorage"
    link: "http://www.w3.org/TR/webstorage/#the-localstorage-attribute"

  - slug: multiplebgs
    title: "CSS Multiple Backgrounds"
    link: "http://www.w3.org/TR/css3-background/#layering"

  - slug: opacity
    title: "CSS opacity"
    link: "http://www.w3.org/TR/css3-color/#transparency"

  - slug: pagedcontent
    title: "CSS Generated Content for Paged Media"
    link: "http://dev.w3.org/csswg/css3-gcpm/"

  - slug: postmessage
    title: "HTML postMessage"
    link: "http://www.whatwg.org/specs/web-apps/current-work/multipage/web-messaging.html#crossDocumentMessages"

  - slug: rgba
    title: "CSS RGBA colors"
    link: "http://www.w3.org/TR/css3-color/#rgba-color"

  - slug: sessionstorage
    title: "Web Storage sessionStorage"
    link: "http://www.w3.org/TR/webstorage/#the-sessionstorage-attribute"

  - slug: smil
    title: "SVG SMIL animation"
    link: "http://www.w3.org/TR/SVG/animate.html"

  - slug: svg
    title: "SVG"
    link: "http://www.w3.org/TR/SVG/"

  - slug: textshadow
    title: "CSS text-shadow"
    link: "http://www.w3.org/TR/css3-text/#text-shadow"

  - slug: touch
    title: "Touch Events"
    link: "http://www.w3.org/TR/touch-events/"

  - slug: video
    title: "HTML Video"
    link: "http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#video"

  - slug: webgl
    title: "WebGL"
    link: "https://www.khronos.org/registry/webgl/specs/1.0/"

  - slug: websockets
    title: "WebSocket API"
    link: "http://www.w3.org/TR/websockets/"

  - slug: webworkers
    title: "Web Workers"
    link: "http://www.whatwg.org/specs/web-apps/current-work/multipage/workers.html"