
# Relative to root directory
siteconfig:
  deployFolder: 'deploy'
  demosFolder: 'demos'
  sourceFolder: 'source'
  layoutsFolder: 'layouts'
  panelCSS: 'panel.css'
  panelJS: 'modernizr.js'
  panelClass: 'sd-panel'
  panelTag: 'div'


# Allowed tags: javascript, forms, canvas, content, parser, svg, css, audio, video
demos:
  - slug: pagedcontent
    title: "Paged Content Magic"
    tags: [css]
    support: [pagedcontent]

  - slug: border-salon
    title: "Border Radius Salon"
    tags: [css]
    support: []

  - slug: photo-booth
    title: "Photobooth in Your browser"
    tags: [javascript, canvas]
    support: [getusermedia, video]

  - slug: parallax
    title: "Parallax Shifts"
    tags: [css]
    support: [csstransforms, csstransitions]

  - slug: hixie-keyboard
    title: "Type a key and hear a voice!"
    tags: [audio]
    support: [audio, video]

  - slug: paranoid
    title: "Return of the Retro with a canvas game!"
    tags: [canvas]
    support: [canvas]

  - slug: object-fitness
    title: "Object Fit"
    tags: [css]
    support: [object-fit]

  - slug: rock-piano
    title: "Rock Piano"
    tags: [css]
    support: [audio]

  - slug: tatami
    title: "Tatami"
    tags: [css]
    support: [csstransitions]

  - slug: isometric-city
    title: "An isometric world"
    tags: [css]
    support: [csstransitions]

  - slug: borderradius-fun
    title: "Tinkering with Border Radius"
    tags: [css]
    support: []

  - slug: tweetmap
    title: "A map of tweets from the public timeline"
    tags: [svg]
    support: [svg]
